In [1]:
import numpy as np

In [2]:
numbers = np.array([2, 3, 5, 7, 11])

In [3]:
type(numbers)

numpy.ndarray

In [4]:
numbers

array([ 2,  3,  5,  7, 11])

In [8]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
import numpy as np

In [10]:
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [12]:
import numpy as np

In [14]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [17]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [18]:
integers.dtype

dtype('int32')

In [19]:
floats.dtype

dtype('float64')

In [20]:
integers.ndim

2

In [21]:
floats.ndim

1

In [22]:
integers.shape

(2, 3)

In [23]:
floats.shape

(5,)

In [24]:
integers.size

6

In [25]:
integers.itemsize

4

In [26]:
floats.size

5

In [27]:
floats.itemsize

8

In [29]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


In [30]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

In [31]:
import numpy as np

In [32]:
a = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [33]:
a.ndim

2

In [34]:
a.shape

(2, 5)

In [35]:
import numpy as np

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [39]:
import numpy as np

In [41]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [42]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [43]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [44]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [46]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [48]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [49]:
import numpy as np

In [50]:
np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [51]:
import random

In [52]:
%timeit rolls_list = \
    [random.randrange(1,7) for i in range(0, 6_000_000)]

10.6 s ± 134 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [53]:
import numpy as np

In [54]:
%timeit rolls_array = np.random.randint(1, 7, 60_000_000)

1.21 s ± 42.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [55]:
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

12.1 s ± 100 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [56]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

120 ms ± 2.27 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [57]:
import numpy as np

In [58]:
%timeit sum([x for x in range(10_000_000)])

1.72 s ± 46.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [59]:
%timeit np.arange(10_000_000).sum()

36.7 ms ± 285 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [60]:
import numpy as np

In [61]:
numbers = np.arange(1, 6)

In [62]:
numbers

array([1, 2, 3, 4, 5])

In [63]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [64]:
numbers ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [65]:
numbers

array([1, 2, 3, 4, 5])

In [66]:
numbers += 10

In [67]:
numbers

array([11, 12, 13, 14, 15])

In [68]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [70]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [71]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [72]:
numbers

array([11, 12, 13, 14, 15])

In [73]:
numbers >= 13

array([False, False,  True,  True,  True])

In [74]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [75]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [76]:
numbers == numbers2

array([False, False, False, False, False])

In [77]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [78]:
import numpy as np

In [79]:
np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [1]:
import numpy as np

In [3]:
grades = np.array([[87, 96, 70], [100, 87, 90], 
                  [94, 77, 90], [100, 81, 82]])

In [4]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [5]:
grades.sum()

1054

In [6]:
grades.min()

70

In [7]:
grades.max()

100

In [8]:
grades.mean()

87.83333333333333

In [9]:
grades.std()

8.792357792739987

In [10]:
grades.var()

77.30555555555556

In [11]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [12]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [13]:
import numpy as np

In [14]:
grades = np.random.randint(60, 101, 12).reshape(3, 4)

In [15]:
grades

array([[85, 62, 61, 73],
       [86, 92, 98, 77],
       [70, 91, 89, 93]])

In [16]:
grades.mean()

81.41666666666667

In [17]:
grades.mean(axis=0)

array([80.33333333, 81.66666667, 82.66666667, 81.        ])

In [18]:
grades.mean(axis=1)

array([70.25, 88.25, 85.75])

In [19]:
import numpy as np

In [20]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [21]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [22]:
numbers2 = np.arange(1, 7) * 10

In [23]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [24]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

In [25]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [26]:
numbers3 = numbers2.reshape(2, 3)

In [27]:
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [28]:
numbers4 = np.array([2, 4, 6])

In [29]:
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

In [30]:
import numpy as np

In [32]:
numbers = np.arange(1, 6)

In [33]:
np.power(numbers, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [34]:
import numpy as np

In [35]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                  [94, 77, 90], [100, 81, 82]])

In [36]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [37]:
grades[0,1]

96

In [38]:
grades[1]

array([100,  87,  90])

In [39]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [40]:
grades[[1, 3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [41]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [42]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [43]:
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [44]:
import numpy as np

In [45]:
a = np.arange(1, 16).reshape(3, 5)

In [46]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [47]:
a[1]

array([ 6,  7,  8,  9, 10])

In [48]:
a[[0, 2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [49]:
a[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [50]:
import numpy as np

In [51]:
numbers = np.arange(1, 6)

In [52]:
numbers

array([1, 2, 3, 4, 5])

In [53]:
numbers2 = numbers.view()

In [54]:
numbers2

array([1, 2, 3, 4, 5])

In [55]:
id(numbers)

2183245232528

In [56]:
id(numbers2)

2183245231760

In [57]:
numbers[1] *= 10

In [58]:
numbers2

array([ 1, 20,  3,  4,  5])

In [59]:
numbers

array([ 1, 20,  3,  4,  5])

In [60]:
numbers2[1] /= 10

In [61]:
numbers

array([1, 2, 3, 4, 5])

In [62]:
numbers2

array([1, 2, 3, 4, 5])

In [63]:
numbers2 = numbers[0:3]

In [64]:
numbers2

array([1, 2, 3])

In [65]:
id(numbers)

2183245232528

In [66]:
id(numbers2)

2183245232336

In [67]:
numbers2[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [68]:
numbers[1] *= 20

In [69]:
numbers

array([ 1, 40,  3,  4,  5])

In [70]:
numbers2

array([ 1, 40,  3])

In [71]:
import numpy as np

In [72]:
numbers = np.arange(1, 6)

In [73]:
numbers

array([1, 2, 3, 4, 5])

In [74]:
numbers2 = numbers.copy()

In [75]:
numbers2

array([1, 2, 3, 4, 5])

In [76]:
numbers[1] *= 10

In [77]:
numbers

array([ 1, 20,  3,  4,  5])

In [78]:
numbers2

array([1, 2, 3, 4, 5])

In [79]:
import numpy as np

In [80]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [81]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [82]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [83]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [84]:
grades.resize(1, 6)

In [85]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [86]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [87]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [88]:
flattened = grades.flatten()

In [89]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [90]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [91]:
flattened[0] = 100

In [92]:
flattened

array([100,  96,  70, 100,  87,  90])

In [93]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [94]:
raveled = grades.ravel()

In [95]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [96]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [97]:
raveled[0] = 100

In [98]:
raveled

array([100,  96,  70, 100,  87,  90])

In [99]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [100]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [101]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

In [103]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

In [104]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [105]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [106]:
import numpy as np

In [107]:
a = np.arange(1, 7).reshape(2, 3)

In [108]:
a = np.hstack((a, a))

In [109]:
a = np.vstack((a, a))

In [110]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [111]:
import pandas as pd

In [112]:
grades = pd.Series([87, 100, 94])

In [113]:
grades

0     87
1    100
2     94
dtype: int64

In [114]:
pd.Series(98.6, range(3))

0    98.6
1    98.6
2    98.6
dtype: float64

In [115]:
grades[0]

87

In [116]:
grades.count()

3

In [117]:
grades.mean()

93.66666666666667

In [118]:
grades.min()

87

In [119]:
grades.max()

100

In [120]:
grades.std()

6.506407098647712

In [121]:
grades.describe()

count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64

In [122]:
grades = pd.Series([87, 100, 94], index=['Wally', 'Eva', 'Sam'])

In [123]:
grades

Wally     87
Eva      100
Sam       94
dtype: int64

In [124]:
grades = pd.Series({'Wally': 87, 'Eva': 100, 'Sam': 94})

In [125]:
grades

Wally     87
Eva      100
Sam       94
dtype: int64

In [126]:
grades['Eva']

100

In [127]:
grades.Wally

87

In [128]:
grades.dtype

dtype('int64')

In [129]:
grades.values

array([ 87, 100,  94], dtype=int64)

In [130]:
hardware = pd.Series(['Hammer', 'Saw', 'Wrench'])

In [131]:
hardware

0    Hammer
1       Saw
2    Wrench
dtype: object

In [132]:
hardware.str.contains('a')

0     True
1     True
2    False
dtype: bool

In [133]:
hardware.str.upper()

0    HAMMER
1       SAW
2    WRENCH
dtype: object

In [134]:
import numpy as np

In [135]:
import pandas as pd

In [136]:
temps = np.random.randint(60, 101, 6)

In [137]:
temperatures = pd.Series(temps)

In [138]:
temperatures

0    78
1    86
2    87
3    77
4    72
5    63
dtype: int32

In [139]:
temperatures.min()

63

In [140]:
temperatures.max()

87

In [141]:
temperatures.mean()

77.16666666666667

In [142]:
temperatures.describe()

count     6.000000
mean     77.166667
std       8.975894
min      63.000000
25%      73.250000
50%      77.500000
75%      84.000000
max      87.000000
dtype: float64

In [143]:
import pandas as pd

In [144]:
grades_dict = {'Wally': [87, 96, 70], 'Eva': [100, 87, 90], 
               'Sam': [94, 77, 90], 'Katie':[100, 81, 82],
               'Bob': [83, 65, 85]}

In [145]:
grades = pd.DataFrame(grades_dict)

In [146]:
grades

Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [147]:
grades.index = ['Test1', 'Test2', 'Test3']

In [150]:
grades

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [151]:
grades['Eva']

Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64

In [152]:
grades.Sam

Test1    94
Test2    77
Test3    90
Name: Sam, dtype: int64

In [153]:
grades.loc['Test1']

Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64

In [154]:
grades.iloc[1]

Wally    96
Eva      87
Sam      77
Katie    81
Bob      65
Name: Test2, dtype: int64

In [155]:
grades.loc['Test1':'Test3']

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85

In [156]:
grades.iloc[0:2]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65

In [157]:
grades.loc[['Test1', 'Test3']]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [158]:
grades.iloc[[0, 2]]

Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85

In [159]:
grades.loc['Test1':'Test2', ['Eva', 'Katie']]

Eva  Katie
Test1  100    100
Test2   87     81

In [160]:
grades.iloc[[0, 2], 0:3]

Wally  Eva  Sam
Test1     87  100   94
Test3     70   90   90

In [161]:
grades[grades >= 90]

Wally    Eva   Sam  Katie  Bob
Test1    NaN  100.0  94.0  100.0  NaN
Test2   96.0    NaN   NaN    NaN  NaN
Test3    NaN   90.0  90.0    NaN  NaN

In [162]:
grades[(grades >= 80) & (grades < 90)]

Wally   Eva  Sam  Katie   Bob
Test1   87.0   NaN  NaN    NaN  83.0
Test2    NaN  87.0  NaN   81.0   NaN
Test3    NaN   NaN  NaN   82.0  85.0

In [163]:
grades.at['Test2', 'Eva']

87

In [164]:
grades.iat[2, 0]

70

In [165]:
grades.at['Test2', 'Eva'] = 100

In [166]:
grades.at['Test2', 'Eva']

100

In [167]:
grades.iat[1, 2] = 87

In [168]:
grades.iat[1, 2]

87

In [169]:
grades.describe()

Wally         Eva        Sam       Katie        Bob
count   3.000000    3.000000   3.000000    3.000000   3.000000
mean   84.333333   96.666667  90.333333   87.666667  77.666667
std    13.203535    5.773503   3.511885   10.692677  11.015141
min    70.000000   90.000000  87.000000   81.000000  65.000000
25%    78.500000   95.000000  88.500000   81.500000  74.000000
50%    87.000000  100.000000  90.000000   82.000000  83.000000
75%    91.500000  100.000000  92.000000   91.000000  84.000000
max    96.000000  100.000000  94.000000  100.000000  85.000000

In [170]:
pd.set_option('precision', 2)

In [171]:
grades.describe()

Wally     Eva    Sam   Katie    Bob
count   3.00    3.00   3.00    3.00   3.00
mean   84.33   96.67  90.33   87.67  77.67
std    13.20    5.77   3.51   10.69  11.02
min    70.00   90.00  87.00   81.00  65.00
25%    78.50   95.00  88.50   81.50  74.00
50%    87.00  100.00  90.00   82.00  83.00
75%    91.50  100.00  92.00   91.00  84.00
max    96.00  100.00  94.00  100.00  85.00

In [172]:
grades.mean()

Wally    84.33
Eva      96.67
Sam      90.33
Katie    87.67
Bob      77.67
dtype: float64

In [173]:
grades.T

Test1  Test2  Test3
Wally     87     96     70
Eva      100    100     90
Sam       94     87     90
Katie    100     81     82
Bob       83     65     85

In [174]:
grades.T.describe()

Test1   Test2  Test3
count    5.00    5.00   5.00
mean    92.80   85.80  83.40
std      7.66   13.81   8.23
min     83.00   65.00  70.00
25%     87.00   81.00  82.00
50%     94.00   87.00  85.00
75%    100.00   96.00  90.00
max    100.00  100.00  90.00

In [175]:
grades.T.mean()

Test1    92.8
Test2    85.8
Test3    83.4
dtype: float64

In [176]:
grades.sort_index(ascending=False)

Wally  Eva  Sam  Katie  Bob
Test3     70   90   90     82   85
Test2     96  100   87     81   65
Test1     87  100   94    100   83

In [177]:
grades.sort_index(axis=1)

Bob  Eva  Katie  Sam  Wally
Test1   83  100    100   94     87
Test2   65  100     81   87     96
Test3   85   90     82   90     70

In [178]:
grades.sort_values(by='Test1', axis=1, ascending=False)

Eva  Katie  Sam  Wally  Bob
Test1  100    100   94     87   83
Test2  100     81   87     96   65
Test3   90     82   90     70   85

In [179]:
grades.T.sort_values(by='Test1', ascending=False)

Test1  Test2  Test3
Eva      100    100     90
Katie    100     81     82
Sam       94     87     90
Wally     87     96     70
Bob       83     65     85

In [180]:
import pandas as pd

In [181]:
temps = {'Mon': [68, 89], 'Tues': [71, 93], 'Wed': [66, 82], 
         'Thu': [75, 97], 'Fri': [62, 79]}

In [182]:
temperatures = pd.DataFrame(temps, index=['Low', 'High'])

In [183]:
temperatures

Mon  Tues  Wed  Thu  Fri
Low    68    71   66   75   62
High   89    93   82   97   79

In [184]:
temperatures.loc[:, 'Mon':'Wed']

Mon  Tues  Wed
Low    68    71   66
High   89    93   82

In [185]:
temperatures.loc['Low']

Mon     68
Tues    71
Wed     66
Thu     75
Fri     62
Name: Low, dtype: int64

In [186]:
pd.set_option('precision', 2)

In [187]:
temperatures.mean()

Mon     78.5
Tues    82.0
Wed     74.0
Thu     86.0
Fri     70.5
dtype: float64

In [188]:
temperatures.mean(axis=1)

Low     68.4
High    88.0
dtype: float64